require 'user.basics'
require 'user.keymaps'
require 'user.plugins'
require 'user.colors'
require 'user.telescope'
require 'user.lsp'
require 'user.nvim-cmp'
require 'user.trouble'
require 'user.jester'
-- require 'user.dap'
require 'user.vimspector'
require 'user.luasnip'
require 'user.symbol-outline'
