#!/usr/bin/env bash

# URL of the binary archive and the binary name
url=$1
binary_name=$2

# Create tmp directory
mkdir -p tmp

# Change to tmp directory
cd tmp

# Get the filename and extension from the URL
filename=$(basename $url)
extension="${filename##*.}"

# Download the binary archive
wget $url

# Extract the archive
if [ "$extension" = "zip" ]; then
	unzip $filename
elif [ "$extension" = "gz" ]; then
	tar -xvf $filename
else
	echo "Unsupported file format: $extension"
	exit 1
fi

# Look for the binary in the root of the extracted folder and in a nested bin folder
binary_path=$(find . -type f -name $binary_name -o -path "*/bin/$binary_name")

# Move the binary to ~/.local/bin
mv $binary_path ~/.local/bin

# Go back to the parent directory and remove the tmp directory
cd ..
rm -rf tmp
