#!/bin/bash

author=$1
repo=$2

parent_path=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )

latest_release=$(bash $parent_path/get_release_url $author/$repo)

echo $latest_release

bash $parent_path/dl_and_install_bin $latest_release $repo
