- name: Command line install
  hosts: localhost
  gather_facts: true

  roles:
    - role: gantsign.oh-my-zsh
      users:
        - username: "{{current_user}}"

  tasks:
    - name: Create ~/.local/bin directory if it doesn't exist
      become: true
      become_method: sudo
      file:
        path: ~/.local/bin
        state: directory
        mode: '0755'

    - name: Add ~/.local/bin to the PATH environment variable
      become: true
      become_method: sudo
      lineinfile:
        path: ~/.bashrc
        line: 'export PATH="$PATH:~/.local/bin"'
        state: present
      register: bashrc_changed
      changed_when: bashrc_changed is changed

    - name: Update and Upgrade Apt
      become: true
      become_method: sudo
      apt:
        upgrade: yes
        update_cache: true
        cache_valid_time: 3600
        force_apt_get: true
        
    - name: Install Packages
      become: true
      become_method: sudo
      package:
        name:
          - trash-cli
          - python3-pip
          - silversearcher-ag
          - fd-find

    - name: Ensuring Homebrew Is Installed
      stat:
        path: /home/linuxbrew/.linuxbrew/bin/brew
      register: homebrew_check

    - name: Fail If Homebrew Is Not Installed and install_homebrew_if_missing Is False
      fail:
        msg: Homebrew is missing...Install from http://brew.sh/
      when:
        - not homebrew_check.stat.exists
        - not install_homebrew_if_missing

    - name: Installing Homebrew
      shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      when:
        - not homebrew_check.stat.exists
        - install_homebrew_if_missing


    - name: Instal brew apps
      become: true
      become_method: sudo
      community.general.homebrew:
        name:
          - lazygit
          - dust
          - exa
          - ripgrep
          - bat
          - unzip
          - gh
          - fzf
          - duf
          - ncdu
          - tmux
          - stow
          - sd
          - xh


