---
- name: Command line install
  hosts: localhost
  become: yes
  become_method: sudo
  vars:
    ansible_connection: local
    ansible_python_interpreter: "{{ ansible_playbook_python }}"

  roles:
    - role: gantsign.oh-my-zsh
      users:
        - username: kd

  tasks:
    - name: Create ~/.local/bin directory if it doesn't exist
      become: true
      become_method: sudo
      file:
        path: ~/.local/bin
        state: directory
        mode: '0755' 

    - name: Add ~/.local/bin to the PATH environment variable
      become: true
      become_method: sudo
      lineinfile:
        path: ~/.bashrc
        line: 'export PATH="$PATH:~/.local/bin"'
        state: present
      register: bashrc_changed
      changed_when: bashrc_changed is changed

    - name: Update and Upgrade Apt
      apt: 
        upgrade: yes
        update_cache: true
        cache_valid_time: 3600
        force_apt_get: true


    - name: Install Packages
      package:
        name:
          - stow
          - trash-cli
          - python3-pip 
          - tmux
          - ncdu
          - duf
          - fzf
          - silversearcher-ag
          - unzip

