FROM ubuntu:22.04

ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Moscow


# COPY ./scripts/ /home/
# COPY ./scripts/init.yml /root/init.yml

# RUN bash ~/init

RUN apt-get update && apt install -y software-properties-common git ansible
RUN git clone https://github.com/julian-iaquinandi/dotfiles ~/dotfiles
COPY git_scripts ~/
RUN bash ~/dotfiles/ansible/init
# RUN bash $HOME/dotfiles/ansible/scripts/docker-init

# USER $USER
CMD tail -F /home/root/.bashrc


# ENV USER=kd
# ENV PASSWORD=q

# RUN echo "root:$PASSWORD" | chpasswd

# RUN useradd -u 8877 $USER
# RUN usermod -aG sudo $USER
# RUN apt-get update && apt-get -y install sudo

# RUN sed -i 's/htt[p|ps]:\/\/archive.ubuntu.com\/ubuntu\//mirror:\/\/mirrors.ubuntu.com\/mirrors.txt/g' /etc/apt/sources.list
