FROM ubuntu:22.04

ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Moscow

ENV USER=kd
ENV PASSWORD=q

RUN echo "root:$PASSWORD" | chpasswd

# RUN useradd -u 8877 $USER
# RUN usermod -aG sudo $USER
# RUN apt-get update && apt-get -y install sudo

RUN apt-get update && apt install -y python3 git ansible 
RUN git clone https://github.com/julian-iaquinandi/dotfiles ~/dotfiles

RUN bash $HOME/dotfiles/ansible/scripts/docker-init $PASSWORD

# USER $USER
CMD tail -F /home/root/.bashrc
