return {
	ensure_installed = {
		"rust",
		"lua",
		"typescript",
		"javascript",
		"svelte",
		"sql",
		"c_sharp",
		"css",
		"html",
		"dockerfile",
		"markdown",
		"markdown_inline",
		"yaml",
		"bash",
		"tsx",
		"toml",
		"json",
	},
	incremental_selection = {
		enable = true,
		keymaps = {
			init_selection = "<C-space>",
			node_incremental = "<C-space>",
			scope_incremental = false,
			node_decremental = "<bs>",
		},
	},
}
