---
- name: Command line install
  hosts: localhost
  become: yes
  become_method: sudo
  vars:
    ansible_connection: local
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
  
  roles:
    - role: gantsign.oh-my-zsh
      users:
        - username: kd

  tasks:
    - name: Install Packages
      package:
        name:
          - stow
          - tree
          - trash-cli
          - tmux

    - name: Configure git
      shell:
        cmd: stow git
        chdir: /home/kd/dotfiles/    

    - name: Configure oh-my-zsh
      shell:
        cmd: stow zsh
        chdir: /home/kd/dotfiles/    

    - name: Remove old zsh config
      ansible.builtin.file:
        path: /home/kd/.zshrc
        state: absent

    - name: Create empty zsh config
      file:
        path: "/home/kd/.zshrc"
        state: touch

    - name: Point new config at .cofig/zsh
      lineinfile:
        path: /home/kd/.zshrc
        line: 'source /home/kd/.config/zsh/.zshrc'
        insertbefore: BOF

    - name: Configure tmux
      shell:
        cmd: stow tmux
        chdir: /home/kd/dotfiles/
