---
- name: Command line install
  hosts: localhost
  become: yes
  become_method: sudo
  vars:
    ansible_connection: local
    ansible_python_interpreter: "{{ ansible_playbook_python }}"

  roles:
    - role: gantsign.oh-my-zsh
      users:
        - username: kd

  tasks:
    - name: Create ~/.local/bin directory if it doesn't exist
      become: true
      become_method: sudo
      file:
        path: ~/.local/bin
        state: directory
        mode: '0755' 

    - name: Add ~/.local/bin to the PATH environment variable
      become: true
      become_method: sudo
      lineinfile:
        path: ~/.bashrc
        line: 'export PATH="$PATH:~/.local/bin"'
        state: present
      register: bashrc_changed
      changed_when: bashrc_changed is changed

    - name: Update and Upgrade Apt
      apt: 
        upgrade: yes
        update_cache: true
        cache_valid_time: 3600
        force_apt_get: true


    - name: Install Packages
      package:
        name:
          - stow
          - trash-cli
          - python3-pip 
          - tmux
          - ncdu
          - duf
          - fzf
          - silversearcher-ag
          - unzip

    - name: Retrieve LazyGit latest release version
      shell: 'curl -s "https://api.github.com/repos/jesseduffield/lazygit/releases/latest" | grep -oP ''(?<=tag_name": "v)[^"]*'''
      register: lazygit_version

    - name: Download LazyGit binary archive
      get_url:
        url: "https://github.com/jesseduffield/lazygit/releases/latest/download/lazygit_{{ lazygit_version.stdout }}_Linux_x86_64.tar.gz"
        dest: "/tmp/lazygit.tar.gz"

    - name: Extract LazyGit binary
      shell: tar xf /tmp/lazygit.tar.gz
      args:
        chdir: /tmp

    - name: Install LazyGit binary
      copy:
        src: /tmp/lazygit
        dest: /usr/local/bin/lazygit
        mode: 0755


    - name: Configure git
      shell:
        cmd: stow git
        chdir: /home/kd/dotfiles/    

    - name: Configure oh-my-zsh
      shell:
        cmd: stow zsh
        chdir: /home/kd/dotfiles/    

    - name: Remove old zsh config
      ansible.builtin.file:
        path: /home/kd/.zshrc
        state: absent

    - name: Create empty zsh config
      file:
        path: "/home/kd/.zshrc"
        state: touch

    - name: Point new config at .cofig/zsh
      lineinfile:
        path: /home/kd/.zshrc
        line: 'source /home/kd/.config/zsh/.zshrc'
        insertbefore: BOF

    - name: Configure tmux
      shell:
        cmd: stow tmux
        chdir: /home/kd/dotfiles/    

    - name: Update home folder permissions
      shell:
        cmd: chmod -R a+rwX,o-w /home/kd
        
    - name: Change file ownership, group and permissions
      file:
        path: /home/kd/.config
        state: directory
        recurse: yes
        owner: kd
        group: kd
