---
- name: Install Github Cli
  hosts: localhost
  become: yes
  become_method: sudo

  vars:
    ansible_connection: local
    ansible_python_interpreter: "{{ ansible_playbook_python }}"

  tasks:
    - name: Add github key
      apt_key:
        keyserver: keyserver.ubuntu.com
        id: C99B11DEB97541F0

    - name: Add github repo
      apt_repository:
        repo: https://cli.github.com/packages
        state: present

    - name: Update and Upgrade Apt
      apt: 
        update_cache: true
        cache_valid_time: 3600
        force_apt_get: true

    - name: Install Github
      shell:
        cmd: apt install gh
