---
- name: Neovim Install
  hosts: localhost
  become: yes
  become_method: sudo
#   roles:
#     - gikeymarcia.neovim
  vars:
    ansible_connection: local
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
#     neovim_nightly: true
#     primary_user: kd
#     neovim_pde: true
#     neovim_npm_packages:
#       - neovim
#       - pnpm
#       - yarn
#     neovim_pip_packages:
#       - pynvim
#     neovim_config_dirs:
#       - "/home/{{ primary_user }}/.config/nvim"

  tasks:
    - name: show family
      debug:
        var: ansible_os_family

    - name: Configure neovim
      shell:
        cmd: stow nvim
        chdir: /home/kd/dotfiles/

    - name: Remove compiled packer file
      ansible.builtin.file:
        path: /home/kd/.config/nvim/plugin/packer_compiled.lua
        state: absent

    - name: Packer Install
      shell:
        cmd: git clone --depth 1 https://github.com/wbthomason/packer.nvim /home/kd/.local/share/nvim/site/pack/packer/start/packer.nvim
        chdir: /home/kd/

    - name: Take ownership of .local
      shell:
        cmd: chown -R kd:kd /home/kd/.local

    - name: Create missing dir
      file:
        path: /home/kd/.local/share/nvim/site/pack/packer/opt
        state: directory

    - name: Take ownership of .local/share/nvim
      shell:
        cmd: chown -R kd:kd /home/kd/.local/share/nvim
