---
- name: Install npm global packages
  hosts: localhost

  - name: Install "pnpm" node.js package globally.
    community.general.npm:
      name: pnpm
      global: true

  - name: Install "yarn" node.js package globally.
    community.general.npm:
      name: yarn
      global: true

  # - name: Install "prettierd" node.js package globally.
  #   community.general.npm:
  #     name: "@fsouza/prettierd"
  #     global: true

  - name: Install "neovim" node.js package globally.
    community.general.npm:
      name: neovim
      global: true
