---
- name: Install NVM and node 
  hosts: localhost
  vars:
    ansible_connection: local
    ansible_python_interpreter: '{{ ansible_playbook_python }}'

  tasks:
  - name: Install nvm
    shell: >
      curl https://raw.githubusercontent.com/creationix/nvm/v0.7.0/install.sh | sh
      creates=/home/{{ ansible_user_id }}/.nvm/nvm.sh

  - name: Install node and set version
    shell: >
      /bin/bash -c "source ~/.nvm/nvm.sh && nvm install stable && nvm alias default stable"
      creates=/home/{{ ansible_user_id }}/.nvm/alias
