- hosts: localhost
  gather_facts: true
  become: true
  become_user: "{{ lookup('env', 'USER') }}"
  become_method: sudo

  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      become_user: root
      changed_when: False
  vars:
    user: "{{ ansible_user_id }}"

  tasks:
    - name: check if cargo is installed
      shell: command -v cargo
      register: cargo_exists
      ignore_errors: yes

    - name: Download Installer
      when: cargo_exists is failed
      get_url:
        url: https://sh.rustup.rs
        dest: /tmp/sh.rustup.rs
        mode: '0755'
        force: 'yes'
      tags:
        - rust

    - name: install rust/cargo
      when: cargo_exists is failed
      shell: /tmp/sh.rustup.rs -y
      tags:
        - rust

    - name: Reload zsh
      command: omz reload

    - name: Install ripgrep Rust package
      community.general.cargo:
        name: ripgrep

    - name: Install "fd" Rust package
      community.general.cargo:
        name: fd-find

    - name: Install "sd" Rust package
      community.general.cargo:
        name: sd

    - name: Install "exa" Rust package
      community.general.cargo:
        name: exa

    - name: Install "dust" Rust package
      community.general.cargo:
        name: du-dust

    - name: Install "xh" Rust package
      community.general.cargo:
        name: xh

    - name: Install "bat" Rust package
      community.general.cargo:
        name: bat

    - name: Install "bat" Rust package
      community.general.cargo:
        name: bob-nvim


