---
- name: Generate SSH Key
  hosts: localhost
  become: yes
  become_method: sudo

  vars:
    ansible_connection: local
    ansible_python_interpreter: "{{ ansible_playbook_python }}"

  tasks:
    - name: Generate an OpenSSH keypair with the default values (4096 bits, rsa)
      shell:
        cmd: ssh-keygen -t rsa -b 4096 -C "kensledev@gmail.com"

