- name: generate SSH key
  hosts: 127.0.0.1
  connection: local
  vars:
    ssh_key_filename: id_rsa
  tasks:
  
    - name: create ssh dir
      file:
        path: /home/kd/.ssh
        state: directory
        mode: '0755'
        
    - name: generate SSH key "{{ssh_key_filename}}"
      openssh_keypair:
        path: "~/.ssh/{{ssh_key_filename}}"
        type: rsa
        size: 4096
        state: present
        force: no
