---
- name: Main playbook
  hosts: localhost
  become: yes
  vars:
    ansible_become_pass: "q"


  tasks:
    - name: Run sub-playbook
      ansible.builtin.include_tasks: ./base/ubuntu_base_install_test.yml
