- name: Download exa
  shell: cd ~ && wget https://github.com/ogham/exa/releases/download/v0.10.1/exa-linux-x86_64-v0.10.1.zip

- name: Unzip file
  shell: cd ~ && unzip exa-linux-x86_64-v0.10.1.zip

- name: Copy extracted files
  copy:
    src: "~/bin/exa"
    dest: "~/.local/bin/"
    remote_src: true

- name: Make file executable
  file:
    path: "~/.local/bin/exa"
    mode: "u+x"

