- name: Download bob
  shell: cd ~ && wget https://github.com/MordechaiHadad/bob/releases/download/v2.3.2/bob-linux-x86_64.zip

- name: Unzip file
  shell: cd ~ && unzip bob-linux-x86_64.zip

- name: Copy extracted files
  copy:
    src: "~/bob"
    dest: "~/.local/bin/"
    remote_src: true

- name: Make file executable
  file:
    path: "~/.local/bin/bob"
    mode: "u+x"
