# - name: Download bob
#   shell: cd ~ && wget https://github.com/MordechaiHadad/bob/releases/download/v2.3.2/bob-linux-x86_64.zip
#
# - name: Unzip file
#   shell: cd ~ && unzip bob-linux-x86_64.zip
#
# - name: Copy extracted files
#   copy:
#     src: "~/bob"
#     dest: "~/.local/bin/"
#     remote_src: true
#
# - name: Make file executable
#   file:
#     path: "~/.local/bin/bob"
#     mode: "u+x"
#
- name: Install neovim
  shell: ~/.local/bin/bob install stable && ~/.local/bin/bob use stable

- name: Configure jujuvim
  shell: cd ~/dotfiles && stow jujuvim
