#!/bin/bash

# Set default values
app_repo_url='https://github.com/MordechaiHadad/app/releases/download/v2.3.2'
app_zip_file='app-linux-x86_64.zip'
app_bin_directory=~/.local/bin
app_bin_name='bob'

# Parse command line arguments
while [[ $# -gt 0 ]]; do
  case $1 in
    --repo-url)
      app_repo_url=$2
      shift
      shift
      ;;
    --zip-file)
      app_zip_file=$2
      shift
      shift
      ;;
    --bin-directory)
      app_bin_directory=$2
      shift
      shift
      ;;
    --bin-name)
      app_bin_name=$2
      shift
      shift
      ;;
    *)
      echo "Unknown argument: $1"
      exit 1
      ;;
  esac
done

# Download application
wget "$app_repo_url"

# Unzip application
unzip "$app_zip_file"

# Make directories
mkdir -p "$app_bin_directory"

# Move application
mv "$app_bin_name" "$app_bin_directory"

# Clean up
rm -r "$app_zip_file"

# Make executable
chmod +x "$app_bin_directory/$app_bin_name"
