- name: Update and Upgrade Apt
  apt:
    upgrade: yes
    update_cache: true
    cache_valid_time: 3600
    force_apt_get: true

- name: Install Packages
  package:
    name:
      - curl
      - trash-cli
      - python3-pip
      - silversearcher-ag
      - fd-find
      - ripgrep
      - bat
      - unzip
      - fzf
      - duf
      - ncdu
      - tmux
      - stow

- name: Configure tmux
  shell:
    cmd: cd ~/dotfiles && stow tmux

- name: Configure git
  shell:
    cmd: cd ~/dotfiles && stow git

# - name: Source zsh
#   shell: . ~/.zshrc
#
# - name: Check for exa bin
#   stat:
#     path: /home/linuxbrew/.linuxbrew/bin/exa
#   register: exa_bin
#
# # - name: Instal brew apps
# #   community.general.homebrew:
# #     name:
# #       - lazygit
# #       - dust
# #       - gh
# #       - sd
# #       - xh
# #       - exa
# - name: test
#   shell: brew install dust
#   when:  exa_bin.stat.exists == false
