- name: Update and Upgrade Apt
  apt:
    upgrade: yes
    update_cache: true
    cache_valid_time: 3600
    force_apt_get: true

- name: Configure local bin
  shell:
    cmd: cd ~/dotfiles && stow bin

- name: Install Apt Packages
  package:
    name:
      - curl
      - trash-cli
      - python3-pip
      - silversearcher-ag
      - fd-find
      - ripgrep
      # - bat
      - unzip
      - fzf
      - duf
      - ncdu
      - tmux
      - stow
      - jq

- name: Install exa
  shell: /usr/bin/env bash ~/.local/bin/git_installer ogham exa

# - name: Install gh
#   shell: /usr/bin/env bash ~/.local/bin/git_installer cli cli

- name: Install bat
  shell: /usr/bin/env bash ~/.local/bin/git_installer sharkdp bat

- name: Install sd
  shell: /usr/bin/env bash ~/.local/bin/git_installer chmin sd

- name: Install xh
  shell: /usr/bin/env bash ~/.local/bin/git_installer ducaale xh

# Configure
- name: Configure tmux
  shell:
    cmd: cd ~/dotfiles && stow tmux

- name: Configure git
  shell:
    cmd: cd ~/dotfiles && stow git

