require 'user.plugins'
require 'user.basics'
require 'user.keymaps'
require 'user.colors'
require 'user.telescope'
-- require 'user.lsp'
-- require 'user.lspn'
require 'user.lspn.mason'
require 'user.lspn.lspconfig'
require 'user.lspn.lspsaga'
require 'user.omnisharp'
require 'user.nvim-cmp'
require 'user.trouble'
require 'user.luasnip'
-- require 'user.symbol-outline'
-- require 'user.dap'
-- require 'user.vimspector'
